apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-sa-role
  namespace: default
subjects:
- kind: ServiceAccount
  name: cicd-sa
  namespace: default
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io
