apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80         # Port accessible from browser
      targetPort: 5000 # Port your app is running inside the container
